# Generated by Django 5.1 on 2024-09-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_release_date',
            field=models.DateField(auto_now=True),
        ),
    ]
